# Generated by Django 2.2.6 on 2019-10-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0003_reparation_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparation',
            old_name='date_installaion',
            new_name='date_reparation',
        ),
    ]
