# Generated by Django 2.2.6 on 2019-11-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0004_auto_20191031_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Site', to='cam.Site'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='nom',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
