# Generated by Django 2.2.6 on 2019-11-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0005_auto_20191101_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Camera', to='cam.Camera'),
        ),
    ]
