# Generated by Django 2.2.6 on 2019-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0007_auto_20191101_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='nom',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='descriptif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(max_length=300),
        ),
    ]
