# Generated by Django 2.2.6 on 2019-11-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0008_auto_20191101_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='frais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
