# Generated by Django 2.2.6 on 2019-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0009_camera_frais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
            ],
        ),
    ]
