# Generated by Django 2.2.6 on 2019-11-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0010_emplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='emplacement',
        ),
        migrations.AddField(
            model_name='camera',
            name='emplacement',
            field=models.ManyToManyField(to='cam.Emplacement'),
        ),
    ]
