# Generated by Django 2.2.6 on 2019-11-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0011_auto_20191114_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='emplacement',
            new_name='emplacements',
        ),
    ]
