# Generated by Django 2.2.6 on 2019-11-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0012_auto_20191114_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='reference',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
