# Generated by Django 2.2.6 on 2019-11-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0014_cameraemplacement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraEmplacement',
            new_name='Cam',
        ),
    ]
