# Generated by Django 2.2.6 on 2019-11-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0015_auto_20191114_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Camera_id', to='cam.Camera'),
        ),
    ]
