# Generated by Django 2.2.6 on 2019-11-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0016_auto_20191115_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.Camera'),
        ),
    ]
