# Generated by Django 2.2.6 on 2019-11-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0018_auto_20191116_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cam',
        ),
    ]
