# Generated by Django 2.2.6 on 2019-11-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0019_delete_cam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.Camera')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.Emplacement')),
            ],
        ),
    ]
