# Generated by Django 2.2.6 on 2019-11-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0020_cam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cam',
            new_name='EmplacementCamera',
        ),
    ]
