# Generated by Django 2.2.6 on 2019-12-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0022_auto_20191204_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacementcamera',
            name='reparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cam.Reparation'),
        ),
    ]
