# Generated by Django 2.2.6 on 2019-12-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0025_auto_20191205_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacement',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cam.Site'),
        ),
    ]
