# Generated by Django 2.2.6 on 2019-12-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0026_emplacement_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='site',
        ),
    ]
