# Generated by Django 2.2.6 on 2019-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0030_auto_20191205_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='emplacements',
        ),
        migrations.AddField(
            model_name='camera',
            name='emplacements',
            field=models.ManyToManyField(to='cam.Emplacement'),
        ),
    ]
