# Generated by Django 2.2.6 on 2019-12-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0031_auto_20191205_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='emplacements',
        ),
    ]
