# Generated by Django 2.2.6 on 2019-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0032_remove_camera_emplacements'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='emplacements',
            field=models.ManyToManyField(through='cam.EmplacementCamera', to='cam.Emplacement'),
        ),
    ]
