# Generated by Django 2.2.6 on 2019-12-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0033_camera_emplacements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('societé', models.CharField(max_length=200)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
