# Generated by Django 2.2.6 on 2019-12-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0034_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam.Fournisseur'),
        ),
    ]
