# Generated by Django 2.2.6 on 2019-12-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0038_remove_camera_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacementcamera',
            name='reparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cam.Reparation'),
        ),
    ]
